before:
  hooks:
    - go mod download

builds:
-
  binary: main
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64

archives:
-
  format: zip
  name_template: "{{ .ProjectName }}-{{ .Version }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
